import tkinter
def Aceptar():
    global caja
    print("Hola Mundo: "+str(caja.get()))
Ventana = tkinter.Tk()
Ventana.title("Ejemplo de botones")
Ventana.geometry("300x200")
etiqueta = tkinter.Label(Ventana, text="Hola Mundo")
#etiqueta.pack()
etiqueta.grid(row=0, column=0)
caja = tkinter.Entry(Ventana)
#caja.pack()
caja.grid(row=0, column=1)
lista = tkinter.Listbox(Ventana)
lista.grid(row=1, column=0)
lista.insert(1, "Python")
lista.insert(2, "Java")
lista.insert(3, "C++")
mivariable = tkinter.StringVar()
radio = tkinter.Radiobutton(Ventana, text="Masculino", variable=mivariable, value="M")
radio.grid(row=2, column=0)
radio = tkinter.Radiobutton(Ventana, text="Femenino",  variable=mivariable, value="F")
radio.grid(row=2, column=1)
check = tkinter.Checkbutton(Ventana, text="Opcion 1")
check.grid(row=3, column=0)
check = tkinter.Checkbutton(Ventana, text="Opcion 2")
check.grid(row=3, column=1)
boton = tkinter.Button(Ventana, text="Aceptar", command=Aceptar)
boton.grid(row=4, column=0)
Ventana.mainloop()